#!/usr/bin/env python3
"""Generate the two GitHub Actions workflows from the real fixture calendar.

§12.1 asks for the prediction job to be scheduled at "deadline + 5 minutes,
per-gameweek from the real deadline list, not a fixed weekly cron". GitHub cron
cannot express that directly:

* there is no year field, so an entry fires every year — harmless, because the
  job re-checks the real deadline and exits if it is not in the window;
* granularity is five minutes;
* runs are queued and routinely delayed 5-20 minutes under load.

So each deadline gets several attempts, the job guards itself on the real
window, and it refuses to publish once the first kickoff has gone. Duplicate
cron lines across gameweeks collapse, which keeps the file readable.

The data job runs weekly per §4, daily as a safety net, plus a few times after
each round's last kickoff so a gameweek that goes Final at the weekend is
published the same day rather than sitting behind a Tuesday cron — which is
also what stops §9.5's stale banner crying wolf every weekend.

Several attempts, not one, with a daily backstop behind them: a round is Final
only once FPL confirms bonus, and that is on FPL's clock, not ours. GW1
confirmed roughly fourteen hours after its last whistle — after every per-round
attempt had already fired — so without the daily line the settled pot would
have waited for the next round's crons, days later, while the page went on
saying "bonus pending".

Usage:  python3 tools/gen_workflows.py [--offline]
"""

from __future__ import annotations

import argparse
from datetime import timedelta
from pathlib import Path

import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from superf import snapshot as snapshot_mod
from superf.config import ROOT
from superf.fpl import Fetcher, FetchError
from superf.fplcal import parse_utc

WORKFLOWS = ROOT / ".github" / "workflows"

PREDICT_OFFSETS = [5, 20, 40]  # minutes after the deadline
DATA_OFFSETS_HOURS = [3, 6, 12]  # after each round's last kickoff

BANNER = (
    "# GENERATED by tools/gen_workflows.py — do not edit by hand.\n"
    "# Cron has no year field, so each line fires annually; the job checks the\n"
    "# real deadline and exits unless it is genuinely inside the window.\n"
)


def cron_lines(moments) -> list[str]:
    seen, out = set(), []
    for moment in sorted(moments):
        line = f"{moment.minute} {moment.hour} {moment.day} {moment.month} *"
        if line not in seen:
            seen.add(line)
            out.append(line)
    return out


def build(fetcher: Fetcher) -> tuple[str, str]:
    # The season mirror carries the same calendar the offline rebuild uses
    # (§4.2), so the workflows can be regenerated on a machine with no HTTP
    # cache and no network — the committed raw/ is enough.
    try:
        bootstrap = fetcher.bootstrap()
        fixtures = fetcher.fixtures()
        events = bootstrap["events"]
    except FetchError:
        season = snapshot_mod.load_season()
        if season is None:
            raise
        events = season["events"]
        fixtures = season["fixtures"]

    deadlines = [parse_utc(e["deadline_time"]) for e in events]
    predict_moments = [
        deadline + timedelta(minutes=offset)
        for deadline in deadlines
        for offset in PREDICT_OFFSETS
    ]

    last_kickoff: dict[int, object] = {}
    for fixture in fixtures:
        if fixture.get("event") is None or not fixture.get("kickoff_time"):
            continue
        gw = int(fixture["event"])
        kickoff = parse_utc(fixture["kickoff_time"])
        if gw not in last_kickoff or kickoff > last_kickoff[gw]:
            last_kickoff[gw] = kickoff
    data_moments = [
        moment + timedelta(hours=offset)
        for moment in last_kickoff.values()
        for offset in DATA_OFFSETS_HOURS
    ]

    predict_cron = "\n".join(f'    - cron: "{c}"' for c in cron_lines(predict_moments))
    data_cron = "\n".join(f'    - cron: "{c}"' for c in cron_lines(data_moments))

    data_yml = f"""{BANNER}name: data.json

on:
  schedule:
    # Weekly, Tuesday 06:00 Malaysia time (§4).
    - cron: "0 22 * * 1"
    # Daily safety net, 14:00 Malaysia time. The per-round attempts below are
    # timed off the last kickoff, but a round goes Final only when FPL confirms
    # bonus, and that is on FPL's clock: GW1 confirmed ~14h after its last
    # whistle, after every per-round attempt had fired, so the settled pot
    # would have waited days for the next round's crons while the page still
    # said "bonus pending". One line bounds that for every round.
    - cron: "0 6 * * *"
    # Plus {', '.join(f'{h}h' for h in DATA_OFFSETS_HOURS)} after each round's last kickoff, so a
    # gameweek that goes Final at the weekend is published the same day — with
    # retries, because the round is only Final once FPL confirms bonus, and a
    # single early attempt would leave it unsettled until the daily cron.
{data_cron}
  workflow_dispatch:

concurrency:
  group: publish
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run the ledger tests
        # A ledger that does not balance is never published (§3.8.5), so the
        # maths is proven before the fetcher is allowed to touch the site.
        run: python -m pytest -q

      - name: Build data.json
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{{{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}}}
          SHEET_ID: ${{{{ secrets.SHEET_ID }}}}
        run: python build.py -v

      - name: Score any outstanding prediction
        env:
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          ANTHROPIC_MODEL: ${{{{ vars.ANTHROPIC_MODEL }}}}
        run: python predict.py --score -v

      - name: Commit
        # Every payout becomes a commit, so `git log` is the audit trail (§4).
        run: |
          git config user.name  "superf-bot"
          git config user.email "superf-bot@users.noreply.github.com"
          for path in docs data backups; do
            [ -e "$path" ] && git add "$path"
          done
          if git diff --cached --quiet; then
            echo "nothing changed"
          else
            THROUGH=$(python -c "import json;print(json.load(open('docs/data.json'))['settled']['through_gw'])")
            git commit -m "data: settled through GW${{THROUGH}}"
            git pull --rebase --autostash
            git push
          fi
"""

    predict_yml = f"""{BANNER}name: prediction.json

# §12.1: squad picks are not public before the deadline, so this runs in the gap
# between the deadline and the first kickoff. Each deadline gets {len(PREDICT_OFFSETS)} attempts
# because Actions cron is queued and routinely delayed; whichever lands first
# publishes, and the rest exit as no-ops.
#
# "Routinely delayed" undersells it. GW2's three attempts were scheduled 17:35,
# 17:50 and 18:10 and all three ran after 01:00 the next morning — seven hours
# past a window only 85 minutes wide, so the round got no call at all. Scheduled
# runs therefore pass --mid-round-if-late: if the blind window has gone, call
# the fixtures that have not kicked off instead. That call is published as
# MID-ROUND and never counts towards the §12.3 record, which is what keeps the
# record about blind calls only.

on:
  schedule:
{predict_cron}
  workflow_dispatch:
    inputs:
      gw:
        description: "Gameweek to call (blank = auto)"
        required: false
      force:
        description: "Ignore the timing window"
        type: boolean
        default: false
      mid_round:
        description: "Call the rest of a gameweek already in progress"
        type: boolean
        default: false

concurrency:
  group: publish
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Predict
        env:
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          ANTHROPIC_MODEL: ${{{{ vars.ANTHROPIC_MODEL }}}}
        run: |
          python predict.py -v \\
            ${{{{ github.event_name == 'schedule' && '--mid-round-if-late' || '' }}}} \\
            ${{{{ inputs.gw && format('--gw {{0}}', inputs.gw) || '' }}}} \\
            ${{{{ inputs.force && '--force' || '' }}}} \\
            ${{{{ inputs.mid_round && '--mid-round' || '' }}}}

      - name: Commit
        run: |
          git config user.name  "superf-bot"
          git config user.email "superf-bot@users.noreply.github.com"
          git add docs
          if git diff --cached --quiet; then
            echo "no prediction published this run"
          else
            GW=$(python -c "import json;print(json.load(open('docs/prediction.json'))['gw'])")
            git commit -m "prediction: GW${{GW}}"
            git pull --rebase --autostash
            git push
          fi
"""
    return data_yml, predict_yml


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--offline", action="store_true")
    args = parser.parse_args()

    WORKFLOWS.mkdir(parents=True, exist_ok=True)
    data_yml, predict_yml = build(Fetcher(offline=args.offline))
    (WORKFLOWS / "data.yml").write_text(data_yml)
    (WORKFLOWS / "predict.yml").write_text(predict_yml)

    print(f"data.yml     {data_yml.count('- cron:')} cron entries")
    print(f"predict.yml  {predict_yml.count('- cron:')} cron entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
