#!/usr/bin/env python3
"""Generate the two GitHub Actions workflows from the real fixture calendar.

§12.1 asks for the prediction job to be scheduled at "deadline + 5 minutes,
per-gameweek from the real deadline list, not a fixed weekly cron". GitHub cron
cannot express that directly:

* there is no year field, so an entry fires every year — harmless, because the
  job re-checks the real deadline and exits if it is not in the window;
* granularity is five minutes;
* runs are queued and routinely delayed 5-20 minutes under load.

So each deadline gets several attempts, the job guards itself on the real
window, and it refuses to publish once the first kickoff has gone. Duplicate
cron lines across gameweeks collapse, which keeps the file readable.

The data job runs weekly per §4, plus once a few hours after each round's last
kickoff so a gameweek that goes Final at the weekend is published the same day
rather than sitting behind a Tuesday cron — which is also what stops §9.5's
stale banner crying wolf every weekend.

Usage:  python3 tools/gen_workflows.py [--offline]
"""

from __future__ import annotations

import argparse
from datetime import timedelta
from pathlib import Path

import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from superf.config import ROOT
from superf.fpl import Fetcher
from superf.fplcal import parse_utc

WORKFLOWS = ROOT / ".github" / "workflows"

PREDICT_OFFSETS = [5, 20, 40]  # minutes after the deadline
DATA_AFTER_LAST_KICKOFF_HOURS = 3

BANNER = (
    "# GENERATED by tools/gen_workflows.py — do not edit by hand.\n"
    "# Cron has no year field, so each line fires annually; the job checks the\n"
    "# real deadline and exits unless it is genuinely inside the window.\n"
)


def cron_lines(moments) -> list[str]:
    seen, out = set(), []
    for moment in sorted(moments):
        line = f"{moment.minute} {moment.hour} {moment.day} {moment.month} *"
        if line not in seen:
            seen.add(line)
            out.append(line)
    return out


def build(fetcher: Fetcher) -> tuple[str, str]:
    bootstrap = fetcher.bootstrap()
    fixtures = fetcher.fixtures()

    deadlines = [parse_utc(e["deadline_time"]) for e in bootstrap["events"]]
    predict_moments = [
        deadline + timedelta(minutes=offset)
        for deadline in deadlines
        for offset in PREDICT_OFFSETS
    ]

    last_kickoff: dict[int, object] = {}
    for fixture in fixtures:
        if fixture.get("event") is None or not fixture.get("kickoff_time"):
            continue
        gw = int(fixture["event"])
        kickoff = parse_utc(fixture["kickoff_time"])
        if gw not in last_kickoff or kickoff > last_kickoff[gw]:
            last_kickoff[gw] = kickoff
    data_moments = [
        moment + timedelta(hours=DATA_AFTER_LAST_KICKOFF_HOURS)
        for moment in last_kickoff.values()
    ]

    predict_cron = "\n".join(f'    - cron: "{c}"' for c in cron_lines(predict_moments))
    data_cron = "\n".join(f'    - cron: "{c}"' for c in cron_lines(data_moments))

    data_yml = f"""{BANNER}name: data.json

on:
  schedule:
    # Weekly, Tuesday 06:00 Malaysia time (§4).
    - cron: "0 22 * * 1"
    # Plus roughly {DATA_AFTER_LAST_KICKOFF_HOURS}h after each round's last kickoff, so a gameweek
    # that goes Final at the weekend is published the same day.
{data_cron}
  workflow_dispatch:

concurrency:
  group: publish
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run the ledger tests
        # A ledger that does not balance is never published (§3.8.5), so the
        # maths is proven before the fetcher is allowed to touch the site.
        run: python -m pytest -q

      - name: Build data.json
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{{{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}}}
          SHEET_ID: ${{{{ secrets.SHEET_ID }}}}
        run: python build.py -v

      - name: Score any outstanding prediction
        env:
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          ANTHROPIC_MODEL: ${{{{ vars.ANTHROPIC_MODEL }}}}
        run: python predict.py --score -v

      - name: Commit
        # Every payout becomes a commit, so `git log` is the audit trail (§4).
        run: |
          git config user.name  "superf-bot"
          git config user.email "superf-bot@users.noreply.github.com"
          for path in docs raw backups; do
            [ -e "$path" ] && git add "$path"
          done
          if git diff --cached --quiet; then
            echo "nothing changed"
          else
            THROUGH=$(python -c "import json;print(json.load(open('docs/data.json'))['settled']['through_gw'])")
            git commit -m "data: settled through GW${{THROUGH}}"
            git pull --rebase --autostash
            git push
          fi
"""

    predict_yml = f"""{BANNER}name: prediction.json

# §12.1: squad picks are not public before the deadline, so this runs in the gap
# between the deadline and the first kickoff. Each deadline gets {len(PREDICT_OFFSETS)} attempts
# because Actions cron is queued and routinely delayed; whichever lands first
# publishes, and the rest exit as no-ops.

on:
  schedule:
{predict_cron}
  workflow_dispatch:
    inputs:
      gw:
        description: "Gameweek to call (blank = auto)"
        required: false
      force:
        description: "Ignore the timing window"
        type: boolean
        default: false

concurrency:
  group: publish
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Predict
        env:
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          ANTHROPIC_MODEL: ${{{{ vars.ANTHROPIC_MODEL }}}}
        run: |
          python predict.py -v \\
            ${{{{ inputs.gw && format('--gw {{0}}', inputs.gw) || '' }}}} \\
            ${{{{ inputs.force && '--force' || '' }}}}

      - name: Commit
        run: |
          git config user.name  "superf-bot"
          git config user.email "superf-bot@users.noreply.github.com"
          git add docs
          if git diff --cached --quiet; then
            echo "no prediction published this run"
          else
            GW=$(python -c "import json;print(json.load(open('docs/prediction.json'))['gw'])")
            git commit -m "prediction: GW${{GW}}"
            git pull --rebase --autostash
            git push
          fi
"""
    return data_yml, predict_yml


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--offline", action="store_true")
    args = parser.parse_args()

    WORKFLOWS.mkdir(parents=True, exist_ok=True)
    data_yml, predict_yml = build(Fetcher(offline=args.offline))
    (WORKFLOWS / "data.yml").write_text(data_yml)
    (WORKFLOWS / "predict.yml").write_text(predict_yml)

    print(f"data.yml     {data_yml.count('- cron:')} cron entries")
    print(f"predict.yml  {predict_yml.count('- cron:')} cron entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
